apiVersion: v1
kind: Service
metadata:
  name: openshift-webtty
  namespace: helm
spec:
  ports:
    - name: openshift-webtty
      port: 9123
      targetPort: 9123
      nodePort: 32121
  selector:
    name: openshift-webtty
  type: LoadBalancer
