apiVersion: v1
kind: ReplicationController
metadata: 
  labels: 
    name: openshift-webtty
  name: openshift-webtty
  namespace: helm
spec: 
  replicas: 1
  selector: 
    name: openshift-webtty
  template: 
    metadata: 
      labels: 
        name: openshift-webtty
      name: openshift-webtty
      namespace: helm
    spec: 
      containers: 
      - image: "tangfeixiong/openshift-webtty:v1.3.0-alpha.1"
        imagePullPolicy: IfNotPresent
        name: openshift-webtty
        ports: 
        - containerPort: 9123
          name: http-p9123
